-- ============================================================
-- Snowflake RBAC Roles for Contoso Bank Loan Platform
-- ============================================================

USE DATABASE CONTOSO_LOAN_DB;

-- ── Create roles ──────────────────────────────────────────

CREATE ROLE IF NOT EXISTS CONTOSO_ADMIN
    COMMENT = 'Full administrative access to the Contoso Loan platform';

CREATE ROLE IF NOT EXISTS CONTOSO_DATA_ENGINEER
    COMMENT = 'Read/write access to all zones; can run Snowpark transforms';

CREATE ROLE IF NOT EXISTS CONTOSO_ANALYST
    COMMENT = 'Read-only access to CURATED_ZONE and REFERENCE for reporting';

CREATE ROLE IF NOT EXISTS CONTOSO_QA
    COMMENT = 'Read access to QA_ZONE and CURATED_ZONE for quality reviews';

-- ── Role hierarchy ────────────────────────────────────────

GRANT ROLE CONTOSO_DATA_ENGINEER TO ROLE CONTOSO_ADMIN;
GRANT ROLE CONTOSO_ANALYST       TO ROLE CONTOSO_ADMIN;
GRANT ROLE CONTOSO_QA            TO ROLE CONTOSO_ADMIN;

-- ── Warehouse grants ──────────────────────────────────────

GRANT USAGE ON WAREHOUSE CONTOSO_TRANSFORM_WH  TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE CONTOSO_REPORTING_WH  TO ROLE CONTOSO_ANALYST;
GRANT USAGE ON WAREHOUSE CONTOSO_REPORTING_WH  TO ROLE CONTOSO_QA;
GRANT USAGE ON WAREHOUSE CONTOSO_TRANSFORM_WH  TO ROLE CONTOSO_ADMIN;
GRANT USAGE ON WAREHOUSE CONTOSO_REPORTING_WH  TO ROLE CONTOSO_ADMIN;

-- ── Database grants ───────────────────────────────────────

GRANT USAGE ON DATABASE CONTOSO_LOAN_DB TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE ON DATABASE CONTOSO_LOAN_DB TO ROLE CONTOSO_ANALYST;
GRANT USAGE ON DATABASE CONTOSO_LOAN_DB TO ROLE CONTOSO_QA;
GRANT USAGE ON DATABASE CONTOSO_LOAN_DB TO ROLE CONTOSO_ADMIN;

-- ── Schema grants ─────────────────────────────────────────

-- Data engineer: full access to all schemas
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA CONTOSO_LOAN_DB.RAW_ZONE     TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW              ON SCHEMA CONTOSO_LOAN_DB.QA_ZONE       TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW              ON SCHEMA CONTOSO_LOAN_DB.REFERENCE      TO ROLE CONTOSO_DATA_ENGINEER;

-- Analyst: read-only on CURATED_ZONE and REFERENCE
GRANT USAGE ON SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE TO ROLE CONTOSO_ANALYST;
GRANT USAGE ON SCHEMA CONTOSO_LOAN_DB.REFERENCE    TO ROLE CONTOSO_ANALYST;

-- QA: read on CURATED_ZONE and QA_ZONE, write to QA_ZONE
GRANT USAGE ON SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE TO ROLE CONTOSO_QA;
GRANT USAGE, CREATE TABLE ON SCHEMA CONTOSO_LOAN_DB.QA_ZONE TO ROLE CONTOSO_QA;

-- ── Table-level grants ────────────────────────────────────

-- Analyst: SELECT on all curated tables
GRANT SELECT ON ALL TABLES IN SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE TO ROLE CONTOSO_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CONTOSO_LOAN_DB.REFERENCE    TO ROLE CONTOSO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE TO ROLE CONTOSO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONTOSO_LOAN_DB.REFERENCE    TO ROLE CONTOSO_ANALYST;

-- QA: SELECT on curated + INSERT/SELECT on QA zone
GRANT SELECT ON ALL TABLES IN SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE   TO ROLE CONTOSO_QA;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CONTOSO_LOAN_DB.QA_ZONE TO ROLE CONTOSO_QA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONTOSO_LOAN_DB.CURATED_ZONE   TO ROLE CONTOSO_QA;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA CONTOSO_LOAN_DB.QA_ZONE TO ROLE CONTOSO_QA;

-- ── Procedure execution grants ────────────────────────────

GRANT USAGE ON PROCEDURE CURATED_ZONE.sp_load_borrower_360()             TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE ON PROCEDURE CURATED_ZONE.sp_load_loan_application_curated() TO ROLE CONTOSO_DATA_ENGINEER;
GRANT USAGE ON PROCEDURE CURATED_ZONE.sp_load_collateral_summary()       TO ROLE CONTOSO_DATA_ENGINEER;
