-- ============================================================
-- Create all tables in CONTOSO_LOAN_DB
-- ============================================================

USE DATABASE CONTOSO_LOAN_DB;

-- ── RAW_ZONE ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS RAW_ZONE.LOAN_APPLICATION_CLEANED (
    APPLICATION_ID      VARCHAR(20)     NOT NULL,
    CUSTOMER_ID         VARCHAR(20),
    BRANCH_CODE         VARCHAR(10)     NOT NULL,
    LOAN_AMOUNT         NUMBER(18,2)    NOT NULL,
    LOAN_TYPE           VARCHAR(20)     NOT NULL,
    APPLICATION_DATE    DATE,
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    SSN_HASH            VARCHAR(64),
    PHONE_NUMBER        VARCHAR(20),
    ADDRESS_LINE1       VARCHAR(200),
    CITY                VARCHAR(100),
    STATE_CODE          CHAR(2),
    ZIP_CODE            VARCHAR(5),
    EMAIL_HASH          VARCHAR(64),
    COLLATERAL_VALUE    NUMBER(18,2),
    SOURCE_SYSTEM       VARCHAR(50),
    LOAD_TIMESTAMP      TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LOAN_APPLICATION_CLEANED PRIMARY KEY (APPLICATION_ID)
);

-- ── REFERENCE ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS REFERENCE.BRANCH_REF (
    BRANCH_CODE         VARCHAR(10)     NOT NULL,
    BRANCH_NAME         VARCHAR(200)    NOT NULL,
    REGION              VARCHAR(100)    NOT NULL,
    STATE_CODE          CHAR(2)         NOT NULL,
    IS_ACTIVE           BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_BRANCH_REF PRIMARY KEY (BRANCH_CODE)
);

-- ── CURATED_ZONE ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS CURATED_ZONE.BORROWER_360 (
    APPLICATION_ID          VARCHAR(20)     NOT NULL,
    CUSTOMER_ID             VARCHAR(20),
    FIRST_NAME              VARCHAR(100),
    LAST_NAME               VARCHAR(100),
    LOAN_AMOUNT             NUMBER(18,2)    NOT NULL,
    LOAN_TYPE               VARCHAR(20)     NOT NULL,
    COLLATERAL_VALUE        NUMBER(18,2),
    APPLICATION_DATE        DATE,
    BRANCH_CODE_NORMALIZED  VARCHAR(10),
    BRANCH_NAME             VARCHAR(200),
    REGION                  VARCHAR(100),
    RISK_TIER               VARCHAR(10),
    TRANSFORMED_AT          TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_BORROWER_360 PRIMARY KEY (APPLICATION_ID)
);

CREATE TABLE IF NOT EXISTS CURATED_ZONE.LOAN_APPLICATION_CURATED (
    APPLICATION_ID      VARCHAR(20)     NOT NULL,
    CUSTOMER_ID         VARCHAR(20),
    BRANCH_CODE         VARCHAR(10)     NOT NULL,
    BRANCH_NAME         VARCHAR(200),
    REGION              VARCHAR(100),
    LOAN_AMOUNT         NUMBER(18,2)    NOT NULL,
    LOAN_TYPE           VARCHAR(20)     NOT NULL,
    APPLICATION_DATE    DATE,
    STATE_CODE          CHAR(2),
    ZIP_CODE            VARCHAR(5),
    COLLATERAL_VALUE    NUMBER(18,2),
    IS_SECURED          BOOLEAN         NOT NULL DEFAULT FALSE,
    CURATED_AT          TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LOAN_APPLICATION_CURATED PRIMARY KEY (APPLICATION_ID)
);

CREATE TABLE IF NOT EXISTS CURATED_ZONE.COLLATERAL_SUMMARY (
    LOAN_TYPE               VARCHAR(20)     NOT NULL,
    REGION                  VARCHAR(100),
    APPLICATION_COUNT       NUMBER(10,0)    NOT NULL,
    TOTAL_LOAN_AMOUNT       NUMBER(18,2)    NOT NULL,
    TOTAL_COLLATERAL_VALUE  NUMBER(18,2),
    AVG_LTV                 NUMBER(8,4),
    SUMMARY_DATE            DATE            NOT NULL,
    SUMMARIZED_AT           TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_COLLATERAL_SUMMARY PRIMARY KEY (LOAN_TYPE, REGION, SUMMARY_DATE)
);

-- ── QA_ZONE ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS QA_ZONE.DQ_EXCEPTION_REPORT (
    EXCEPTION_ID        VARCHAR(36)     NOT NULL DEFAULT UUID_STRING(),
    RUN_TIMESTAMP       TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    INPUT_FILE          VARCHAR(500),
    TOTAL_RECORDS       NUMBER(10,0),
    TOTAL_FAILURES      NUMBER(10,0),
    ROW_INDEX           NUMBER(10,0),
    FIELD_NAME          VARCHAR(100),
    RULE_NAME           VARCHAR(100),
    ACTUAL_VALUE        VARCHAR(500),
    MESSAGE             VARCHAR(1000),
    SEVERITY            VARCHAR(20),
    CONSTRAINT PK_DQ_EXCEPTION_REPORT PRIMARY KEY (EXCEPTION_ID)
);
